spring:
  application:
    name: printing-pulse
  profiles:
    active: local  # 기본적으로 local 프로파일 사용
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop  # 테스트용
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:sdk926@gmail.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

thingiverse:
  api:
    base-url: https://api.thingiverse.com
    token: ${THINGIVERSE_API_TOKEN}

server:
  port: 8080

logging:
  level:
    # org.hibernate.SQL: debug
    org.springframework.web: info
